### ISSUE TITLE
Links no Footer não funcionam nas telas de Cadastro Coletor e Cadastro Ponto Coleta

### ISSUE THREAD

**Issue by gkshida** [eNove/front.recolhe.eco#1]
- Minha resolução é 1366x768, os links não funcionam;
- Ao diminuir o zoom da página para 67% os links começam a funcionar;
- Testei no Firefox e no Chrome no PC.

![recolhe-eco-issue](https://user-images.githubusercontent.com/3990881/96525267-e692dc00-1250-11eb-9a6e-be7a71cdc860.gif)

**Comment by degadev451** [comment]
Obrigado Guilherme.
